// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TABLE_ZIV_HALL_TABLE_H_
#define FLATBUFFERS_GENERATED_TABLE_ZIV_HALL_TABLE_H_

#include "flatbuffers/flatbuffers.h"

namespace ziv {
namespace hall {
namespace table {

struct SetdownRequest;

struct SetdownReply;

struct LeaveRequest;

struct LeaveReply;

struct Message;

enum Any {
  Any_NONE = 0,
  Any_SetdownRequest = 1,
  Any_SetdownReply = 2,
  Any_LeaveRequest = 3,
  Any_LeaveReply = 4,
  Any_MIN = Any_NONE,
  Any_MAX = Any_LeaveReply
};

inline Any (&EnumValuesAny())[5] {
  static Any values[] = {
    Any_NONE,
    Any_SetdownRequest,
    Any_SetdownReply,
    Any_LeaveRequest,
    Any_LeaveReply
  };
  return values;
}

inline const char **EnumNamesAny() {
  static const char *names[] = {
    "NONE",
    "SetdownRequest",
    "SetdownReply",
    "LeaveRequest",
    "LeaveReply",
    nullptr
  };
  return names;
}

inline const char *EnumNameAny(Any e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesAny()[index];
}

template<typename T> struct AnyTraits {
  static const Any enum_value = Any_NONE;
};

template<> struct AnyTraits<SetdownRequest> {
  static const Any enum_value = Any_SetdownRequest;
};

template<> struct AnyTraits<SetdownReply> {
  static const Any enum_value = Any_SetdownReply;
};

template<> struct AnyTraits<LeaveRequest> {
  static const Any enum_value = Any_LeaveRequest;
};

template<> struct AnyTraits<LeaveReply> {
  static const Any enum_value = Any_LeaveReply;
};

bool VerifyAny(flatbuffers::Verifier &verifier, const void *obj, Any type);
bool VerifyAnyVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct SetdownRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERID = 4
  };
  const flatbuffers::String *playerId() const {
    return GetPointer<const flatbuffers::String *>(VT_PLAYERID);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYERID) &&
           verifier.Verify(playerId()) &&
           verifier.EndTable();
  }
};

struct SetdownRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_playerId(flatbuffers::Offset<flatbuffers::String> playerId) {
    fbb_.AddOffset(SetdownRequest::VT_PLAYERID, playerId);
  }
  explicit SetdownRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SetdownRequestBuilder &operator=(const SetdownRequestBuilder &);
  flatbuffers::Offset<SetdownRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetdownRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetdownRequest> CreateSetdownRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> playerId = 0) {
  SetdownRequestBuilder builder_(_fbb);
  builder_.add_playerId(playerId);
  return builder_.Finish();
}

inline flatbuffers::Offset<SetdownRequest> CreateSetdownRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *playerId = nullptr) {
  return ziv::hall::table::CreateSetdownRequest(
      _fbb,
      playerId ? _fbb.CreateString(playerId) : 0);
}

struct SetdownReply FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_CODE = 4,
    VT_TABLEID = 6,
    VT_SEAT = 8
  };
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  const flatbuffers::String *tableId() const {
    return GetPointer<const flatbuffers::String *>(VT_TABLEID);
  }
  int32_t seat() const {
    return GetField<int32_t>(VT_SEAT, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CODE) &&
           VerifyOffset(verifier, VT_TABLEID) &&
           verifier.Verify(tableId()) &&
           VerifyField<int32_t>(verifier, VT_SEAT) &&
           verifier.EndTable();
  }
};

struct SetdownReplyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(SetdownReply::VT_CODE, code, 0);
  }
  void add_tableId(flatbuffers::Offset<flatbuffers::String> tableId) {
    fbb_.AddOffset(SetdownReply::VT_TABLEID, tableId);
  }
  void add_seat(int32_t seat) {
    fbb_.AddElement<int32_t>(SetdownReply::VT_SEAT, seat, 0);
  }
  explicit SetdownReplyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SetdownReplyBuilder &operator=(const SetdownReplyBuilder &);
  flatbuffers::Offset<SetdownReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetdownReply>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetdownReply> CreateSetdownReply(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t code = 0,
    flatbuffers::Offset<flatbuffers::String> tableId = 0,
    int32_t seat = 0) {
  SetdownReplyBuilder builder_(_fbb);
  builder_.add_seat(seat);
  builder_.add_tableId(tableId);
  builder_.add_code(code);
  return builder_.Finish();
}

inline flatbuffers::Offset<SetdownReply> CreateSetdownReplyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t code = 0,
    const char *tableId = nullptr,
    int32_t seat = 0) {
  return ziv::hall::table::CreateSetdownReply(
      _fbb,
      code,
      tableId ? _fbb.CreateString(tableId) : 0,
      seat);
}

struct LeaveRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TABLEID = 4
  };
  const flatbuffers::String *tableId() const {
    return GetPointer<const flatbuffers::String *>(VT_TABLEID);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TABLEID) &&
           verifier.Verify(tableId()) &&
           verifier.EndTable();
  }
};

struct LeaveRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_tableId(flatbuffers::Offset<flatbuffers::String> tableId) {
    fbb_.AddOffset(LeaveRequest::VT_TABLEID, tableId);
  }
  explicit LeaveRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LeaveRequestBuilder &operator=(const LeaveRequestBuilder &);
  flatbuffers::Offset<LeaveRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LeaveRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<LeaveRequest> CreateLeaveRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> tableId = 0) {
  LeaveRequestBuilder builder_(_fbb);
  builder_.add_tableId(tableId);
  return builder_.Finish();
}

inline flatbuffers::Offset<LeaveRequest> CreateLeaveRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *tableId = nullptr) {
  return ziv::hall::table::CreateLeaveRequest(
      _fbb,
      tableId ? _fbb.CreateString(tableId) : 0);
}

struct LeaveReply FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_CODE = 4
  };
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CODE) &&
           verifier.EndTable();
  }
};

struct LeaveReplyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(LeaveReply::VT_CODE, code, 0);
  }
  explicit LeaveReplyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LeaveReplyBuilder &operator=(const LeaveReplyBuilder &);
  flatbuffers::Offset<LeaveReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LeaveReply>(end);
    return o;
  }
};

inline flatbuffers::Offset<LeaveReply> CreateLeaveReply(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t code = 0) {
  LeaveReplyBuilder builder_(_fbb);
  builder_.add_code(code);
  return builder_.Finish();
}

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_OBJECT_TYPE = 4,
    VT_OBJECT = 6
  };
  Any object_type() const {
    return static_cast<Any>(GetField<uint8_t>(VT_OBJECT_TYPE, 0));
  }
  const void *object() const {
    return GetPointer<const void *>(VT_OBJECT);
  }
  template<typename T> const T *object_as() const;
  const SetdownRequest *object_as_SetdownRequest() const {
    return object_type() == Any_SetdownRequest ? static_cast<const SetdownRequest *>(object()) : nullptr;
  }
  const SetdownReply *object_as_SetdownReply() const {
    return object_type() == Any_SetdownReply ? static_cast<const SetdownReply *>(object()) : nullptr;
  }
  const LeaveRequest *object_as_LeaveRequest() const {
    return object_type() == Any_LeaveRequest ? static_cast<const LeaveRequest *>(object()) : nullptr;
  }
  const LeaveReply *object_as_LeaveReply() const {
    return object_type() == Any_LeaveReply ? static_cast<const LeaveReply *>(object()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_OBJECT_TYPE) &&
           VerifyOffset(verifier, VT_OBJECT) &&
           VerifyAny(verifier, object(), object_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SetdownRequest *Message::object_as<SetdownRequest>() const {
  return object_as_SetdownRequest();
}

template<> inline const SetdownReply *Message::object_as<SetdownReply>() const {
  return object_as_SetdownReply();
}

template<> inline const LeaveRequest *Message::object_as<LeaveRequest>() const {
  return object_as_LeaveRequest();
}

template<> inline const LeaveReply *Message::object_as<LeaveReply>() const {
  return object_as_LeaveReply();
}

struct MessageBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_object_type(Any object_type) {
    fbb_.AddElement<uint8_t>(Message::VT_OBJECT_TYPE, static_cast<uint8_t>(object_type), 0);
  }
  void add_object(flatbuffers::Offset<void> object) {
    fbb_.AddOffset(Message::VT_OBJECT, object);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MessageBuilder &operator=(const MessageBuilder &);
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    Any object_type = Any_NONE,
    flatbuffers::Offset<void> object = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_object(object);
  builder_.add_object_type(object_type);
  return builder_.Finish();
}

inline bool VerifyAny(flatbuffers::Verifier &verifier, const void *obj, Any type) {
  switch (type) {
    case Any_NONE: {
      return true;
    }
    case Any_SetdownRequest: {
      auto ptr = reinterpret_cast<const SetdownRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Any_SetdownReply: {
      auto ptr = reinterpret_cast<const SetdownReply *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Any_LeaveRequest: {
      auto ptr = reinterpret_cast<const LeaveRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Any_LeaveReply: {
      auto ptr = reinterpret_cast<const LeaveReply *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool VerifyAnyVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAny(
        verifier,  values->Get(i), types->GetEnum<Any>(i))) {
      return false;
    }
  }
  return true;
}

inline const ziv::hall::table::Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<ziv::hall::table::Message>(buf);
}

inline const char *MessageIdentifier() {
  return "tabl";
}

inline bool MessageBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, MessageIdentifier());
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ziv::hall::table::Message>(MessageIdentifier());
}

inline const char *MessageExtension() {
  return "mon";
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ziv::hall::table::Message> root) {
  fbb.Finish(root, MessageIdentifier());
}

}  // namespace table
}  // namespace hall
}  // namespace ziv

#endif  // FLATBUFFERS_GENERATED_TABLE_ZIV_HALL_TABLE_H_
